name: IONOS.space

on: [push]

jobs:
  ionos-space:
    runs-on: ubuntu-latest
    steps:
      - name: Get Ionos Project data
        uses: ionos-deploy-now/retrieve-project-info-action@v1
        id: project
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          project: 5b91a50f-5805-4398-89f4-912135c48287
          service-host: api-us.ionos.space
      - name: checkout
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Deploy to IONOS
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: ionos-deploy-now/deploy-to-ionos-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          remote-host: ${{ steps.project.outputs.remote-host }}
          dist-folder: ./
          project: 5b91a50f-5805-4398-89f4-912135c48287
          storage-quota: ${{ steps.project.outputs.storage-quota }}
          branch-id: ${{ steps.project.outputs.branch-id }}
          service-host: api-us.ionos.space
